TTITLE 'Employee Report'
BTITLE 'Confidential'
COLUMN JOB HEADING 'Job|Category'
COLUMN ENAME HEADING 'Employee'
COLUMN SAL JUSTIFY LEFT FORMAT $99,999.99
COLUMN SAL HEADING 'Salary'
select JOB,ENAME,SAL
FROM EMP
WHERE SAL<3000;
