ACCEPT value CHAR PROMPT 'Please enter the location name:';
COLUMN DNAME HEADING 'Department|Name'
COLUMN ENAME HEADING 'EMPLOYEE|Name'
COLUMN HIRDATE HEADING 'STATE|DATE'
COLUMN SAL JUSTIFY LEFT FORMAT $99,999.99
COLUMN SAL HEADING 'SALARY'
COLUMN SAL*12 JUSTIFY LEFT FORMAT $99,999.99
COLUMN SAL*12 HEADING 'ANNUAL|SALARY'
select DNAME,ENAME,HIREDATE,SAL,SAL*12
FROM EMP,DEPT
WHERE DEPT.DEPTNO=EMP.DEPTNO AND DEPT.LOC='&value';
